---
extends: existence
message: "'%s' is too wordy."
ignorecase: true
level: warning
tokens:
  - a number of
  - accede to
  - adjacent to
  - adversely impact
  - all of
  - all things considered
  - along the lines of
  - already existing
  - alternatively
  - as a matter of fact
  - as a means of
  - as far as I'm concerned
  - as of yet
  - as to
  - as yet
  - at the present time
  - at this time
  - attributable to
  - because of the fact that
  - benefit from
  - by means of
  - by virtue of
  - by virtue of the fact that
  - close proximity
  - comply with
  - due to the fact that
  - each and every
  - first and foremost
  - for all intents and purposes
  - for the most part
  - for the purpose of
  - have a tendency to
  - honest truth
  - if and when
  - in a manner of speaking
  - in a timely manner
  - in a very real sense
  - in accordance with
  - in all likelihood
  - in an effort to
  - in between
  - in excess of
  - in lieu of
  - in light of the fact that
  - in many cases
  - in my opinion
  - in order to
  - in regard to
  - in some instances
  - in terms of
  - in the case of
  - in the event that
  - in the final analysis
  - in the nature of
  - in the near future
  - in the process of
  - incumbent upon
  - is applicable to
  - is authorized to
  - is responsible for
  - it is
  - it is essential
  - it seems that
  - it was
  - not certain
  - not many
  - not often
  - not unless
  - not unlike
  - notwithstanding
  - null and void
  - on the contrary
  - on the other hand
  - one particular
  - optimum
  - overall
  - owing to the fact that
  - pass away
  - pertaining to
  - point in time
  - prior to
  - provided that
  - put simply
  - readily apparent
  - refer back
  - regarding
  - relocate
  - should you wish
  - span across
  - successfully complete
  - the month of
  - the point I am trying to make
  - time period
  - took advantage of
  - type of
  - until such time as
  - various different
  - what I mean to say is
  - whether or not
  - with the exception of
