(define-module (tests tests)
  #:use-module (ice-9 pretty-print))

(define (pp . args)
  (for-each (lambda (arg) (pretty-print arg)) args))

(define (pp-if . args)
  "Only pretty-print ARGS if this is the main script"
  (if (equal? (car (command-line)) "tests/tests.scm")
      (pp args)))

(pp-if "Testing Channels")
(use-modules (kbg channels))
(pp-if "Testing Profiles")
(use-modules (kbg packages profiles base))
(use-modules (kbg packages profiles desktop))
(use-modules (kbg packages profiles development))
(use-modules (kbg packages profiles emacs))
(use-modules (kbg packages profiles fonts))
(use-modules (kbg packages profiles laptop))
(use-modules (kbg packages profiles science))
(use-modules (kbg packages profiles statistics))
(use-modules (kbg packages profiles video))
(pp-if "Testing Services")
(use-modules (kbg services boltd))
(use-modules (kbg services borg))
(use-modules (kbg services dbus))
(use-modules (kbg services desktop))
(use-modules (kbg services dict))
(use-modules (kbg services gnupg))
(use-modules (kbg services languagetool))
(use-modules (kbg services mpd))
(use-modules (kbg services nftables))
(use-modules (kbg services parallel))
(use-modules (kbg services shell))
(use-modules (kbg services shepherd))
(use-modules (kbg services slurm))
(use-modules (kbg services syncthing))
(pp-if "Testing Config Services")
(use-modules (kbg services config aspell))
(use-modules (kbg services config borg))
(use-modules (kbg services config chktex))
(use-modules (kbg services config direnv))
(use-modules (kbg services config dotfiles))
(use-modules (kbg services config emacs))
(use-modules (kbg services config email))
(use-modules (kbg services config fontconfig))
(use-modules (kbg services config git))
(use-modules (kbg services config global))
(use-modules (kbg services config gnupg))
(use-modules (kbg services config gnuplot))
(use-modules (kbg services config guile))
(use-modules (kbg services config guix))
(use-modules (kbg services config haskell))
(use-modules (kbg services config kitty))
(use-modules (kbg services config languagetool))
(use-modules (kbg services config ledger))
(use-modules (kbg services config maven))
(use-modules (kbg services config mpd))
(use-modules (kbg services config nixpkgs))
(use-modules (kbg services config nyxt))
(use-modules (kbg services config parallel))
(use-modules (kbg services config pdfpc))
(use-modules (kbg services config shepherd))
(use-modules (kbg services config ssh))
(use-modules (kbg services config tmux))
(use-modules (kbg services config vale))
(use-modules (kbg services config vars))
(use-modules (kbg services config wallpaper))
(use-modules (kbg services config xdg))
(use-modules (kbg services config xresources))
(use-modules (kbg services timers recoll))
(use-modules (kbg services timers borg))
(use-modules (kbg system mcron))
(use-modules (kbg system xorg))
(pp-if "Testing Homes")
(use-modules (homes axo))
(use-modules (homes bard))
(use-modules (homes koi))
(use-modules (homes owl))
(use-modules (homes yak))
(pp-if "Testing Systems")
(use-modules (systems axo))
(use-modules (systems bard))
(use-modules (systems owl))
(use-modules (systems yak))
