(define-module (kbg services config xdg)
  #:use-module (gnu home services)
  #:use-module (gnu home services xdg)
  #:export (xdg-config-service))

(define xdg-config-service
  (list (service home-xdg-mime-applications-service-type
                 (home-xdg-mime-applications-configuration
                  (added '((image/png . gimp.desktop)
                           (image/jpeg . gimp.desktop)))
                  (default '((all/text . emacsclient)
                             (application/pdf . org.gnome.Evince.desktop)
                             (application/jpg . (eog gimp.desktop))
                             (image/gif . (eog gimp))
                             (image/jpeg . (eog gimp))
                             (image/png . (eog gimp))
                             (image/svg . eog)
                             (image/webp . eog)
                             (inode/direcotory . nautilus)
                             (text/plain . emacsclient)
                             (text/x-java . emacsclient)
                             (text/x-makefile . emacsclient)
                             (text/x-shellscript . emacsclient)
                             (text/html . emacsclient)
                             (x-scheme-handler/http . firefox)
                             (x-scheme-handler/https . firefox)
                             (x-scheme-handler/zoommtg . us.zoom.Zoom)))))
        (service home-xdg-user-directories-service-type
                 (home-xdg-user-directories-configuration
                  (desktop "$HOME/desktop")
                  (documents "$HOME/documents")
                  (download "$HOME/downloads")
                  (music "$HOME/music")
                  (pictures "$HOME/pictures")
                  (publicshare "$HOME/public")
                  (templates "$HOME")
                  (videos "$HOME")))))
