(define-module (kbg services config xdg)
  #:use-module (gnu home services)
  #:use-module (gnu home services xdg)
  #:export (xdg-config-service))

(define xdg-config-service
  (list (service home-xdg-mime-applications-service-type
                 (home-xdg-mime-applications-configuration
                  (added '((image/png . (gimp.desktop))
                           (image/jpeg . (gimp.desktop))))
                  (default '((all/text . (emacsclient.desktop))
                             (application/pdf . (org.gnome.Evince.desktop))
                             (application/jpg . (eog gimp.desktop))
                             (image/gif . (org.gnome.eog.desktop gimp.desktop))
                             (image/jpeg . (org.gnome.eog.desktop gimp.desktop))
                             (image/png . (org.gnome.eog.desktop gimp.desktop))
                             (image/svg . (org.gnome.eog.desktop))
                             (image/webp . (org.gnome.eog.desktop))
                             (inode/direcotory . (nautilus.desktop))
                             (text/plain . (emacsclient.desktop))
                             (text/x-java . (emacsclient.desktop))
                             (text/x-makefile . (emacsclient.desktop))
                             (text/x-shellscript . (emacsclient.desktop))
                             (text/html . (eemacsclient.desktop))
                             (x-scheme-handler/http . (firefox.desktop))
                             (x-scheme-handler/https . (firefox.desktop))
                             (x-scheme-handler/zoommtg . (us.zoom.Zoom.desktop))))))
        (service home-xdg-user-directories-service-type
                 (home-xdg-user-directories-configuration
                  (desktop "$HOME/desktop")
                  (documents "$HOME/documents")
                  (download "$HOME/downloads")
                  (music "$HOME/music")
                  (pictures "$HOME/pictures")
                  (publicshare "$HOME/public")
                  (templates "$HOME")
                  (videos "$HOME/videos")))))
