set mouse-=a
set tabstop=4
set shiftwidth=4
set softtabstop=4
set autoindent
set expandtab
set relativenumber
color molokai
syntax enable
set wrap
set textwidth=79
set colorcolumn=80
highlight OverLength ctermbg=red ctermfg=white guibg=#592929
match OverLength /\%80v.\+/
set encoding=utf-8
set hidden
set backspace=indent,eol,start
set list
set listchars=trail:·
set columns=90
set lines=40
set cursorline
au VimEnter * RainbowParenthesesToggle
au Syntax * RainbowParenthesesLoadRound
au Syntax * RainbowParenthesesLoadSquare
au Syntax * RainbowParenthesesLoadBraces
au Syntax * RainbowParenthesesLoadChevrons
let mapleader = ","
let g:gitgutter_enabled = 0
noremap <leader>r :RainbowParenthesesToggle<CR>
noremap <leader>\ :NERDTreeToggle<CR>
noremap <leader>s :set spell!<CR>
noremap <leader>h :%!xxd<CR>
noremap <leader>d :%!xxd -r<CR>
noremap <leader>g :GitGutterToggle<CR>
noremap <Up> ""
noremap! <Up> <Esc>
noremap <Down> ""
noremap! <Down> <Esc>
noremap <Left> ""
noremap! <Left> <Esc>
noremap <Right> ""
noremap! <Right> <Esc>
set directory=~/.vim/temp
set backupdir=~/.vim/backup
set guioptions-=T
set guioptions-=m
