set nocompatible
filetype off
set rtp+=~/.vim/bundle/vundle
call vundle#rc()
Bundle 'gmarik/vundle'
Bundle 'airblade/vim-gitgutter'
Bundle 'scrooloose/nerdtree'
Bundle 'kien/rainbow_parentheses.vim'
Bundle 'Lokaltog/powerline'
filetype plugin on
set t_Co=256
set tabstop=4
set shiftwidth=4
set softtabstop=4
set autoindent
set expandtab
set relativenumber
syntax enable
color molokai
set wrap
set textwidth=75
set colorcolumn=76
set encoding=utf-8
set hidden
set backspace=indent,eol,start
set list
set listchars=trail:·
set cursorline
set laststatus=2
au VimEnter * RainbowParenthesesToggle
au Syntax * RainbowParenthesesLoadRound
au Syntax * RainbowParenthesesLoadSquare
au Syntax * RainbowParenthesesLoadBraces
au Syntax * RainbowParenthesesLoadChevrons
let mapleader = ","
let g:gitgutter_enabled = 0
noremap <leader>r :RainbowParenthesesToggle<CR>
noremap <leader>\ :NERDTreeToggle<CR>
noremap <leader>s :set spell!<CR>
noremap <leader>h :%!xxd<CR>
noremap <leader>d :%!xxd -r<CR>
noremap <leader>g :GitGutterToggle<CR>
noremap <Up> ""
noremap! <Up> <Esc>
noremap <Down> ""
noremap! <Down> <Esc>
noremap <Left> ""
noremap! <Left> <Esc>
noremap <Right> ""
noremap! <Right> <Esc>
set directory=~/.vim/temp/
set backupdir=~/.vim/backup/
