#!/usr/bin/env bash

function use_guix() {
    GIT_ROOT="$(git rev-parse --show-toplevel)"
    GUIX_CHANNELS="${GIT_ROOT}/channels.scm"
    if [[ -f ${GUIX_CHANNELS} ]]; then
        echo "Using Guix version from ${GUIX_CHANNELS}"
        GUIX_ENVIRONMENT=$(guix time-machine --channels=${GUIX_CHANNELS} -- shell -- bash -c 'echo ${GUIX_ENVIRONMENT}')
        export GUIX_ENVIRONMENT
        eval "$(guix time-machine --channels=${GUIX_CHANNELS} -- shell --search-paths)"
    else
        GUIX_ENVIRONMENT=$(guix shell -- bash -c 'echo ${GUIX_ENVIRONMENT}')
        export GUIX_ENVIRONMENT
        eval "$(guix shell --search-paths)"
    fi
}
