(define-module (kbg services timers guix-gc)
  #:use-module (ice-9 match)
  #:use-module (srfi srfi-1)
  #:use-module (kbg)
  #:use-module (guix)
  #:use-module (guix gexp)
  #:use-module (guix records)
  #:use-module (gnu)
  #:use-module (gnu services)
  #:use-module (gnu services configuration)
  #:use-module (gnu services shepherd)
  #:export (guix-gc-timer))

(define guix-gc-timer
  (shepherd-timer '(guix-gc)
                  #~(calendar-event #:days '(1 15)
                                    #:hours '(12)
                                    #:minutes '(3))
                  #~("/run/current-system/profile/bin/guix"
                     "gc" "--delete-generations=14d")
                  #:requirement '(guix-daemon)))
