NIX_PROFILE="${HOME}/.nix-profile"
PYTHONPATH="${NIX_PROFILE}/lib/python3.7/site-packages${PYTHONPATH:+}"
C_INCLUDE_PATH="${NIX_PROFILE}/include${C_INCLUDE_PATH:+}"
CPLUS_INCLUDE_PATH="${NIX_PROFILE}/include${CPLUS_INCLUDE_PATH:+}"
PATH="${NIX_PROFILE}/bin:${PATH}"
export PATH
export PYTHONPATH
export C_INCLUDE_PATH
export CPLUS_INCLUDE_PATH
