autoload -U compinit promptinit -U colors && colors
compinit
promptinit

alias ls='ls --color=auto'
alias grep='grep --color=always'
alias sudo='sudo -E'

PROMPT="[%n@%m %1~]$ "
RPROMPT="[%{$fg[green]%}%?%{$reset_color%}]"

export EDITOR='vim'
export PATH=$PATH:~/.local/bin

cd ~/
