autoload -U compinit promptinit -U colors && colors
compinit
promptinit
HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zsh_history
setopt inc_append_history
setopt share_history
setopt extended_history

alias ls='ls --color=auto'
alias grep='grep --color=always'
alias sudo='sudo -E'
alias tmux='tmux -2'

export EDITOR='vim'
export PATH=$PATH:~/.local/bin:~/.gem/ruby/latest/bin

if [ -e /usr/share/zsh/site-contrib/powerline.zsh ] &&
   [ "$TERM" = "xterm" ] &&
   [ -z "$SSH_CONNECTION" ]
then
    . /usr/share/zsh/site-contrib/powerline.zsh
else
    PROMPT="[%n@%m %1~]$ "
    prompt_precmd() {
        if [ $? -ne 0 ]; then
            RPROMPT="[%{$fg[green]%}%?%{$reset_color%}]"
        else
            RPROMPT=""
        fi
    }
    precmd_functions+=(prompt_precmd)
fi

cd ~/
