autoload -U compinit promptinit -U colors && colors
compinit
promptinit

alias ls='ls --color=auto'
alias grep='grep --color=always'
alias sudo='sudo -E'
alias tmux='tmux -2'

export EDITOR='vim'
export PATH=$PATH:~/.local/bin

. /usr/share/zsh/site-contrib/powerline.zsh

cd ~/
